services:
  task_app:
    container_name: task-app-container
    build:
      context: .
      dockerfile: Dockerfile
    image: task-app-image:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasks?useSSL=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - keycloak
    restart: on-failure
  mysql:
    container_name: container-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tasks
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
  keycloak:
    container_name: container-keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8085
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info
    command: [ "start-dev", "--http-port", "8085"]
    ports:
      - "8085:8085"
    volumes:
      - keycloak-data:/opt/keycloak/data
volumes:
  mysql-data:
  keycloak-data: