version: '3.8'
services:
#  task_app:
#    container_name: task-app-container
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: task-app-image
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasks?useSSL=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: admin
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    restart: on-failure
  mysql:
    container_name: container-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tasks
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data: