spring:
  profiles:
    active: local
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT:3306}/${DATABASE_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always